{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.workflows.serviceAccount.create }}
{{- $namespaces := list .Release.Namespace }}
{{- if and (not .Values.rbac.singleNamespace) .Values.controller.workflowNamespaces }}
{{- $namespaces = .Values.controller.workflowNamespaces }}
{{- end }}
{{- range $namespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo-workflows.workflows.serviceAccountName" $ }}
  namespace: {{ . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: argo-workflows
  {{- if or $.Values.workflows.serviceAccount.annotations $.Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $.Values.workflows.serviceAccount.annotations $.Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.workflows.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
{{- end }}
