{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-exporter" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- $labels := merge .Values.metrics.service.labels .Values.commonLabels }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if or .Values.metrics.service.annotations .Values.commonAnnotations }}
  {{- $annotations := merge .Values.metrics.service.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  sessionAffinity: {{ .Values.metrics.service.sessionAffinity }}
  {{- if .Values.metrics.service.clusterIP }}
  clusterIP: {{ .Values.metrics.service.clusterIP }}
  {{- end }}
  ports:
    - name: tcp-metrics
      port: {{ .Values.metrics.service.ports.http }}
      protocol: TCP
      targetPort: http
  {{- $podLabels := merge .Values.metrics.podLabels .Values.commonLabels }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: metrics
{{ end }}
