{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.server.enabled .Values.server.metrics.enabled .Values.server.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.fullname" . }}-server
  namespace: {{ default .Release.Namespace .Values.server.metrics.serviceMonitor.namespace | quote }}
  {{- $labels := merge .Values.server.metrics.serviceMonitor.labels .Values.commonLabels }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: server
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.server.metrics.serviceMonitor.jobLabel | quote }}
  selector:
    {{- $svcLabels := merge .Values.server.metrics.serviceMonitor.selector .Values.commonLabels }}
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $svcLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: server
  endpoints:
    - port: metrics
      {{- if .Values.server.metrics.serviceMonitor.interval }}
      interval: {{ .Values.server.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.server.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.server.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.server.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.server.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.server.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.server.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.server.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
{{- end }}
