{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $replicaCount := int .Values.s3.replicaCount }}
{{- if and .Values.filer.enabled .Values.s3.enabled .Values.s3.pdb.create (or (gt $replicaCount 1) .Values.s3.autoscaling.enabled) }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "seaweedfs.s3.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: s3
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.s3.pdb.minAvailable }}
  minAvailable: {{ .Values.s3.pdb.minAvailable }}
  {{- end  }}
  {{- if .Values.s3.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.s3.pdb.maxUnavailable }}
  {{- end  }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.s3.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: s3
{{- end }}
