{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.service.headless.annotations }}
  {{- $annotations := merge .Values.service.headless.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.containerPorts.http }}
    - name: rpc
      port: {{ .Values.containerPorts.rpc }}
    - name: serflan-tcp
      protocol: TCP
      port: {{ .Values.containerPorts.serfLAN }}
    - name: serflan-udp
      protocol: UDP
      port: {{ .Values.containerPorts.serfLAN }}
    - name: rpc-server
      port: {{ .Values.containerPorts.rpcServer }}
    - name: dns-tcp
      port: {{ .Values.containerPorts.dns }}
    - name: dns-udp
      protocol: UDP
      port: {{ .Values.containerPorts.dns }}
  {{- $podLabels := merge .Values.podLabels .Values.commonLabels }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
  sessionAffinity: None
