{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $replicaCount := int .Values.webdav.replicaCount }}
{{- if and .Values.filer.enabled .Values.webdav.enabled .Values.webdav.pdb.create (or (gt $replicaCount 1) .Values.webdav.autoscaling.enabled) }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "seaweedfs.webdav.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: webdav
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webdav.pdb.minAvailable }}
  minAvailable: {{ .Values.webdav.pdb.minAvailable }}
  {{- end  }}
  {{- if .Values.webdav.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.webdav.pdb.maxUnavailable }}
  {{- end  }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.webdav.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: webdav
{{- end }}
